# 1-sketch-to-video
- adapter_lora_scale: 1.0
  adapter_lora_path: "models/Motion_Module/v3_sd15_adapter.ckpt"
  dreambooth_path:    "models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors"

  inference_config: "configs/inference/inference-v3_mask.yaml"
  motion_module:    "models/Motion_Module/v3_sd15_mm.ckpt"

  controlnet_config: "configs/inference/sparsectrl/image_condition.yaml"
  controlnet_path:   "models/SparseCtrl/v3_sd15_sparsectrl_scribble.ckpt"

  seed: -1
  steps: 25
  guidance_scale: 8.5

  controlnet_image_indexs: [0]
  controlnet_images:
    - "__assets__/demos/scribble/forest.png"
    - "__assets__/demos/scribble/forest_contour2.png"      # create your own contour image by using filter_test2.py

  prompt:
     - "twisted leafless forest, a winged griffin standing on a high branch with wings half-spread, feathers ruffled by wind, a giant dragon coiled beside the stream breathing slowly, flowing water, drifting air lines, mystical fairytale mood, sketchy, high contrast, high quality"
     - "dark enchanted forest, bare curling trees, griffin perched on a branch leaning forward as if about to leap, wings slightly raised, calm dragon coiled below with subtle motion in scales, winding stream in motion, swirling lines, fantasy atmosphere, masterpiece"
  n_prompt:
  - "worst quality, low quality, simple line art, flat color, blurry, cropped, text, watermark, deformed, ugly, extra limbs, photo, realistic, plain white background, color, simple background, static"